apiVersion: v1
kind: Secret
metadata:
  name: alaya-harbor-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmhkLTAxLmFsYXlhbmV3LmNvbTo4NDQzIjogewogICAgICAgICAgICAidXNlcm5hbWUiOiAidmMtYXBwLW1hcmtldC12aWV3IiwKICAgICAgICAgICAgInBhc3N3b3JkIjogIkhLc2U1NjPvvIEiCiAgICAgICAgfQogICAgfQp9
  
