apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelName }}
  labels:
    app: {{ .Values.modelName }}
spec:
  ports:
    - port: 8188
      targetPort: 8188
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: {{ .Values.modelName }}