modelName: pytorch-260-py311-ubuntu2204

#如果需要先下载模型，可以选择无卡启动
enableGpu: 1  # 1: 带GPU启动 , 0: 无卡启动




# ====================🚀🚀🚀🚀🚀🚀🚀  GPU 资源说明 🚀🚀🚀🚀🚀🚀🚀====================
# 🏢 北京一区:
#   - NVIDIA-H800A-NV-80G    (标签: nvidia.com/gpu-h100-80gb-hbm3)   配比: 13C:200G:1GPU
#   - NVIDIA-H800-NV-80G     (标签: nvidia.com/gpu-h800)             配比: 18C:200G:1GPU
#   - NVIDIA-L40S-PCIE-48G   (标签: nvidia.com/gpu-l40s)             配比: 10C:100G:1GPU
#
# 🏢 北京二区:
#   - NVIDIA-H800A-NV-80G    (标签: nvidia.com/gpu-h800)             配比: 18C:200G:1GPU
#
# 🏢 北京三区:
#   - NVIDIA-H800E-NV-35G    (标签: nvidia.com/mig-h200-1g.35gb)     配比: 4C:40G:1GPU
#   - NVIDIA-H800E-NV-141G   (标签: nvidia.com/gpu-h200)             配比: 18C:200G:1GPU
# =====================================================================================


#GPU型号   #可以从上面的型中选择,无卡启动这里也不需要修改 ，填写GPU标签
gpuKey: nvidia.com/gpu-l40s
#GPU个数
gpuCount: 1

cpu: 10
memory: 100G

##镜像信息
image: "pytorch-260-py311-ubuntu2204"
tag: "1.1.15"