#apiVersion: v1
#kind: Secret
#metadata:
#  name: alaya-harbor-secret
#type: kubernetes.io/dockerconfigjson
#data:
#  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmhkLTAxLmFsYXlhbmV3LmNvbTo4NDQzIjogewogICAgICAgICAgICAidXNlcm5hbWUiOiAidmMtYXBwLW1hcmtldC12aWV3IiwKICAgICAgICAgICAgInBhc3N3b3JkIjogIkhLc2U1NjPvvIEiCiAgICAgICAgfQogICAgfQp9
#
apiVersion: v1
kind: Secret
metadata:
  name: alaya-harbor-secret
type: kubernetes.io/dockerconfigjson
data:
  {{- if or (not .Values.zoneID) (eq .Values.zoneID "hd-01") }}
  .dockerconfigjson: {{ dict "auths" (dict "registry.hd-01.alayanew.com:8443" (dict "username" "vc-app-market-view" "password" "HKse563！")) | toJson | b64enc }}
  {{- else }}
  .dockerconfigjson: {{ dict "auths" (dict (printf "registry.%s.alayanew.com:8443" .Values.zoneID) (dict "username" "vc-app-market-view" "password" "AlayaNeW1AppMarket2V1ew3Passw0rd4")) | toJson | b64enc }}
  {{- end }}
